server:
  port: 8080

spring:
  main:
    web-application-type: REACTIVE  
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
